---
- name: create instances
  hosts: localhost
  vars:
    keypair: ansible
    security_group: web
    instance_type: t2.micro
    image: ami-f4cc1de2
    region: us-east-1
    subnet_id: subnet-965655e1
  tasks:
    - name: launch instances
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet_id }}"
         count: 1
         instance_tags:
           Name: testansible
      register: ec2
    - debug:
        msg: "{{ ec2 }}"
    - name: EIP 
      ec2_eip:
        in_vpc: yes
        state: present
        region: "{{ region }}"
        instance_id: "{{ ec2.instance_ids[0] }}"
      register: instance_eip

